16 16 N
CE CS CE CS CE CS CE CS CE CS CE CS CE CS CE CS
SN CN CW SS SN CN CW SS SN CN CW SS SN CN CW SS
CN CS CE CW CN CS CE CW CN CS CE CW CN CS CE CW
CE CW CN SE SE CW CN CS CE CW CN SE SE CW CN CS
SN CE SW CS CE SW CS SS SN CE SW CS CE SW CS SS
CN CW CE CW CN CS CN CW CN CW CE CW CN CS CN CW
CE CS CN CS CE CW CE CS CE CS CN CS CE CW CE CS
SN CN SE CW CN SE CW CN CW CN SE CW CN SE CW SS
CN CS CE SW CS CE SW CS CE SW CS CE SW CS CE CW
CE CW CN CS CN CW CE CW CN CS CN CW CE CW CN CS
SN CE CS SS CE CS CN CS CE CW CE CS SN CE CS SS
CN CW CN CW SN CN SE CW CN SE CW SS CN CW CN CW
CE CS CE CS SN CE SW CS CE SW CS SS CE CS CE CS
SN CN CW SS CN CW CE CW CN CS CN CW SN CN CW SS
CN CS CE CW CE CS CN CS CE CW CE CS CN CS CE CW
LE CW CN SE CW CN SE CW CN SE CW CN SE CW CN LW
