#include "game.h"

#ifndef TOOLS_H
#define TOOLS_H

// Tableaux pour la création d'un object game fonctionnel
extern piece p[25];//[25] = {LEAF,LEAF,LEAF,TEE,CORNER,SEGMENT,CORNER,TEE,CORNER,LEAF,TEE,TEE,SEGMENT,LEAF,LEAF,LEAF,TEE,SEGMENT,SEGMENT,CORNER,LEAF,TEE,SEGMENT,SEGMENT,LEAF};
extern direction d[25];//[25] = {N,N,E,N,W,N,E,N,S,S,E,N,E,W,N,S,E,E,E,S,E,S,W,W,W};

// Tableaux déjà fini
extern piece P[25];//[25] = {LEAF,CORNER,LEAF,CORNER,CORNER,CORNER,TEE,TEE,TEE,SEGMENT,LEAF,SEGMENT,TEE,LEAF,LEAF,LEAF,SEGMENT,TEE,CORNER,LEAF,LEAF,SEGMENT,TEE,TEE,LEAF};
extern direction D[25];//[25] = {N,N,W,N,W,E,S,N,W,N,E,W,W,S,S,E,E,W,N,W,E,E,S,S,W};
extern piece P1[25];//[25] = {LEAF,CORNER,LEAF,CORNER,CORNER,CORNER,TEE,TEE,TEE,SEGMENT,LEAF,SEGMENT,TEE,LEAF,LEAF,LEAF,SEGMENT,TEE,CORNER,LEAF,LEAF,SEGMENT,TEE,TEE,LEAF};
extern direction D1[25];//[25] = {N,N,W,N,W,E,S,N,W,N,E,W,W,S,S,E,E,W,N,W,E,E,S,S,W};
extern piece P2[25];//[25] = {CORNER,LEAF,LEAF,LEAF,LEAF,TEE,CORNER,TEE,CORNER,SEGMENT,LEAF,TEE,TEE,TEE,TEE,LEAF,TEE,LEAF,SEGMENT,SEGMENT,LEAF,SEGMENT,SEGMENT,CORNER,LEAF};
extern direction D2[25];//[25] = {N,W,N,N,N,E,W,E,S,S,S,E,S,N,W,E,S,W,S,S,E,E,E,S,S};
extern piece P3[25];//[25] = {LEAF,LEAF,LEAF,CORNER,LEAF,TEE,TEE,LEAF,TEE,TEE,CORNER,TEE,TEE,CORNER,LEAF,CORNER,CORNER,TEE,TEE,LEAF,LEAF,LEAF,CORNER,CORNER,LEAF};
extern direction D3[25];//[25] = {N,N,E,W,N,E,S,W,E,W,E,N,N,S,S,N,S,E,N,W,S,E,S,E,W};

#endif
